version: '3'
services:
  etl-pipeline:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-service
    environment:
      DEBUG: 'true'
    ports:
      - "8050:8050"  
    volumes:
      - ./:/etl-gcs-postgres-bigquery
